# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1186, 1010)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(400, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_capture_front = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_capture_front.setGeometry(QtCore.QRect(20, 50, 171, 41))
        self.btn_capture_front.setObjectName("btn_capture_front")
        self.btn_calculate = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_calculate.setGeometry(QtCore.QRect(20, 120, 191, 41))
        self.btn_calculate.setObjectName("btn_calculate")
        self.btn_capture_side = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_capture_side.setGeometry(QtCore.QRect(200, 50, 181, 41))
        self.btn_capture_side.setObjectName("btn_capture_side")
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_cam_front = QtWidgets.QLabel(self.centralwidget)
        self.lbl_cam_front.setMinimumSize(QtCore.QSize(580, 657))
        self.lbl_cam_front.setObjectName("lbl_cam_front")
        self.horizontalLayout.addWidget(self.lbl_cam_front)
        self.lbl_cam_side = QtWidgets.QLabel(self.centralwidget)
        self.lbl_cam_side.setMinimumSize(QtCore.QSize(580, 657))
        self.lbl_cam_side.setObjectName("lbl_cam_side")
        self.horizontalLayout.addWidget(self.lbl_cam_side)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Results"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Capture"))
        self.btn_capture_front.setText(_translate("MainWindow", "Front Face"))
        self.btn_calculate.setText(_translate("MainWindow", "Calculate"))
        self.btn_capture_side.setText(_translate("MainWindow", "Side Face"))
        self.lbl_cam_front.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_cam_side.setText(_translate("MainWindow", "TextLabel"))
